restart-times: 2
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
jobs: 200
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 6000
use-envmodules: False
use-singularity: False
rerun-incomplete: True
printshellcmds: True
